/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    private static Connection koneksi; //Koneksi

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelhudul = new javax.swing.JPanel();
        labeljudul = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        panelkonten = new javax.swing.JPanel();
        panellogin = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btnmasuk = new javax.swing.JButton();
        cbl = new javax.swing.JCheckBox();
        labelid = new javax.swing.JLabel();
        labelpass = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        labellogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelhudul.setBackground(new java.awt.Color(102, 102, 102));

        labeljudul.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        labeljudul.setForeground(new java.awt.Color(255, 255, 255));
        labeljudul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Book Shelf_48px_2.png"))); // NOI18N
        labeljudul.setText("Perpustakaan");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close Window_20px_6.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize Window_20px_1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelhudulLayout = new javax.swing.GroupLayout(panelhudul);
        panelhudul.setLayout(panelhudulLayout);
        panelhudulLayout.setHorizontalGroup(
            panelhudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhudulLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labeljudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );
        panelhudulLayout.setVerticalGroup(
            panelhudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeljudul)
                .addGap(26, 26, 26))
            .addGroup(panelhudulLayout.createSequentialGroup()
                .addGroup(panelhudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelkonten.setBackground(new java.awt.Color(102, 102, 102));

        panellogin.setBackground(new java.awt.Color(204, 204, 204));
        panellogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtid.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 102, 102));
        txtid.setText("Masukan Username");
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidMouseClicked(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtpass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 102, 102));
        txtpass.setText("Masukan Password");
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassFocusLost(evt);
            }
        });

        btnmasuk.setBackground(new java.awt.Color(204, 204, 204));
        btnmasuk.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnmasuk.setForeground(new java.awt.Color(0, 51, 51));
        btnmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login Rounded Right_20px.png"))); // NOI18N
        btnmasuk.setText("LOGIN");
        btnmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukActionPerformed(evt);
            }
        });

        cbl.setBackground(new java.awt.Color(204, 204, 204));
        cbl.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cbl.setForeground(new java.awt.Color(204, 255, 255));
        cbl.setText("Tampilkan Password");
        cbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cblMouseClicked(evt);
            }
        });
        cbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblActionPerformed(evt);
            }
        });

        labelid.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Circled User Male_25px_6.png"))); // NOI18N
        labelid.setText("Username");

        labelpass.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelpass.setForeground(new java.awt.Color(102, 102, 102));
        labelpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password_25px.png"))); // NOI18N
        labelpass.setText("Password");

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelloginLayout.createSequentialGroup()
                        .addComponent(labelid)
                        .addGap(18, 18, 18)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelloginLayout.createSequentialGroup()
                        .addComponent(labelpass)
                        .addGap(21, 21, 21)
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbl)
                            .addComponent(txtpass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmasuk)
                .addContainerGap())
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelloginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelid))
                .addGap(18, 18, 18)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnmasuk)
                .addContainerGap())
        );

        panelmenu.setBackground(new java.awt.Color(255, 255, 255));

        labellogin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        labellogin.setForeground(new java.awt.Color(0, 51, 51));
        labellogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_25px_2.png"))); // NOI18N
        labellogin.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("|");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Form Login");

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labellogin)
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labellogin)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout panelkontenLayout = new javax.swing.GroupLayout(panelkonten);
        panelkonten.setLayout(panelkontenLayout);
        panelkontenLayout.setHorizontalGroup(
            panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelkontenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelkontenLayout.setVerticalGroup(
            panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkontenLayout.createSequentialGroup()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelhudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelkonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelhudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelkonten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//koneksi

    private static Connection buka_koneksi() {

        if (koneksi == null) {
            try {
                String driver = "com.mysql.jdbc.Driver";
                String url = "jdbc:mysql://localhost:3306/uas_kel4_perpustakaan";
                String user = "root";
                String password = "";

                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi = DriverManager.getConnection(url, user, password);

            } catch (SQLException t) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan " + t.getMessage());
            }
        }
        return koneksi;

    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar"
                + "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
            this.dispose();
        } else {
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        this.setState(this.ICONIFIED);

    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        String kata = "Masukan Username";

        if (txtid.getText().equals(kata)) {
            txtid.setText("");
        }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        String kata = "Masukan Username";
        if (txtid.getText().isEmpty()) {
            txtid.setText(kata);
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMouseClicked

    }//GEN-LAST:event_txtidMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        String kata = "Masukan Password";

        if (txtpass.getText().equals(kata)) {
            txtpass.setEchoChar('*');
            txtpass.setText("");
        }
    }//GEN-LAST:event_txtpassFocusGained

    private void txtpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusLost
        String kata = "Masukan Password";
        if (txtpass.getText().isEmpty()) {
            txtpass.setEchoChar((char) 0);
            txtpass.setText(kata);
        }
    }//GEN-LAST:event_txtpassFocusLost
//koneksi
    private void btnmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukActionPerformed

        try {
            buka_koneksi();
            String sql = "SELECT * FROM login INNER JOIN petugas ON login.id_petugas = petugas.id_petugas WHERE login.username='" + txtid.getText() + "'and login.password='" + txtpass.getText() + "'";
            Statement stat = koneksi.createStatement();
            ResultSet res = stat.executeQuery(sql);

            if (res.next()) {

                JOptionPane.showMessageDialog(null, "Berhasil Login");
                Utama HalUtama = new Utama();
                HalUtama.setVisible(true);
                this.dispose();
            } else {

                JOptionPane.showMessageDialog(this, "Username atau Password salah");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmasukActionPerformed

    private void cblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cblMouseClicked
        if (cbl.isSelected()) {
            txtpass.setEchoChar((char) 0);
        } else {
            txtpass.setEchoChar('*');

        }
    }//GEN-LAST:event_cblMouseClicked

    private void cblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnmasuk.requestFocus();        // TODO add your handling code here:
        txtpass.setEchoChar((char) 0);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmasuk;
    private javax.swing.JCheckBox cbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labellogin;
    private javax.swing.JLabel labelpass;
    private javax.swing.JPanel panelhudul;
    private javax.swing.JPanel panelkonten;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
